import pytest
from backend.command_gatekeeper import CommandGatekeeper
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import ec
import base64
import os

# Assuming keys are already generated by backend import
from backend.auth import admin_private_key, admin_public_key

def test_gatekeeper_signature_verification():
    gatekeeper = CommandGatekeeper()

    command = "STOP"
    target = "factory/line1/machine1/command"
    message = (command + target).encode('utf-8')

    # Valid Signature
    signature = admin_private_key.sign(
        message,
        ec.ECDSA(hashes.SHA256())
    )
    b64_sig = base64.b64encode(signature).decode('utf-8')

    assert gatekeeper.validate(command, target, b64_sig) is True

def test_gatekeeper_invalid_signature():
    gatekeeper = CommandGatekeeper()

    command = "STOP"
    target = "factory/line1/machine1/command"
    message = (command + target).encode('utf-8')

    # Invalid Signature (random bytes)
    invalid_sig = base64.b64encode(os.urandom(64)).decode('utf-8')

    assert gatekeeper.validate(command, target, invalid_sig) is False

def test_gatekeeper_tampered_message():
    gatekeeper = CommandGatekeeper()

    command = "STOP"
    target = "factory/line1/machine1/command"
    message = (command + target).encode('utf-8')

    # Signature for correct message
    signature = admin_private_key.sign(
        message,
        ec.ECDSA(hashes.SHA256())
    )
    b64_sig = base64.b64encode(signature).decode('utf-8')

    # Verify with different command
    assert gatekeeper.validate("START", target, b64_sig) is False
